language: python

python:
  - "3.6"

script: 
  - python3 HelloWorldTest.py

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=1n0t/pyhelloworldtestcicd
  - docker build -f Dockerfile -t $REPO .
  - docker tag $REPO $REPO
  - docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
